=== kodoliti/fluid/fluid-core/target/classes/configuration/fluid-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://kodoliti.org/schema/fluid"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://kodoliti.org/schema/fluid"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">


   <xsd:element name="fluid">
    <xsd:complexType>
      <xsd:sequence>
        <!--xsd:element ref="agendaEventListener" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="processEventListener" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="workingMemoryEventListener" minOccurs="0" maxOccurs="unbounded"/-->

         <xsd:element name="system-conf" minOccurs="1" maxOccurs="1">
            <xsd:complexType>
              <xsd:all minOccurs="0">
                <!--xsd:element ref="persistence" minOccurs="0"/-->

                  <xsd:element name="grid" minOccurs="1" maxOccurs="1">
                      <xsd:complexType>
                          <!--xsd:attribute name="enabled" type="xsd:boolean"/-->
                          <xsd:all>
                              <xsd:element name="nodes" minOccurs="1" maxOccurs="1">
                                  <xsd:complexType>
                                      <xsd:sequence>
                                          <xsd:element name="node" minOccurs="1" maxOccurs="unbounded">
                                               <xsd:complexType>
                                                        <xsd:attribute name="id" type="xsd:string"/>
                                                        <xsd:attribute name="address" type="xsd:string"/>
                                                </xsd:complexType>
                                          </xsd:element>
                                      </xsd:sequence>
                                  </xsd:complexType>
                              </xsd:element>
                          </xsd:all>
                      </xsd:complexType>
                  </xsd:element>

                  <xsd:element name="persistence" minOccurs="1" maxOccurs="1">
                      <xsd:complexType>
                          <!--xsd:attribute name="enabled" type="xsd:boolean"/-->
                          <xsd:all>
                              <xsd:element name="provider" minOccurs="1" maxOccurs="1">
                                  <xsd:complexType>
                                      <xsd:attribute name="type" type="typeProvider"/>
                                  </xsd:complexType>
                              </xsd:element>
                              <xsd:element name="connection-conf" minOccurs="1" maxOccurs="1">
                                  <xsd:complexType>
                                      <xsd:attribute name="driverClass" type="xsd:string"/>
                                      <xsd:attribute name="host" type="xsd:string"/>
                                      <xsd:attribute name="port" type="xsd:string"/>
                                      <xsd:attribute name="username" type="xsd:string"/>
                                      <xsd:attribute name="password" type="xsd:string"/>
                                  </xsd:complexType>
                              </xsd:element>
                          </xsd:all>
                      </xsd:complexType>
                  </xsd:element>


                <!--xsd:element name="clock-type" minOccurs="0">
                  <xsd:complexType>
                    <xsd:attribute name="type" type="clockTypeEnum"/>
                  </xsd:complexType>
                </xsd:element-->

                <!--xsd:element name="work-item-handlers" minOccurs="0">
                  <xsd:complexType>
                    <xsd:choice>
                      <xsd:element name="work-item-handler" minOccurs="0" maxOccurs="unbounded">
                        <xsd:complexType>
                          <xsd:attribute name="name" use="required" type="xsd:string"/>
                          <xsd:attribute name="ref" use="required" type="xsd:string"/>
                        </xsd:complexType>
                      </xsd:element>
                    </xsd:choice>
                  </xsd:complexType>
                </xsd:element-->
              </xsd:all>
            </xsd:complexType>
          </xsd:element>

            <xsd:element name="process-conf" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="diagram" minOccurs="1" maxOccurs="1">
                               <xsd:complexType>
                                 <xsd:attribute name="location" type="xsd:string" />
                               </xsd:complexType>
                        </xsd:element>

                        <xsd:element name="service-tasks" minOccurs="1" maxOccurs="1">

                            <xsd:complexType>
                                <xsd:sequence>
                                         <xsd:element name="task" minOccurs="1" maxOccurs="1">
                                              <xsd:complexType>
                                                        <xsd:attribute name="class" type="xsd:string" use="required" />
                                                </xsd:complexType>
                                        </xsd:element>
                                </xsd:sequence>
                            </xsd:complexType>

                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>



          <!--xsd:element name="batch" minOccurs="0" maxOccurs="1">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="command" minOccurs="0" maxOccurs="unbounded" />
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element-->



          <!--xsd:element name="script" minOccurs="0" maxOccurs="1">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="command" minOccurs="0" maxOccurs="unbounded" />
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element-->


      </xsd:sequence>
   <!--xsd:attribute name="type" use="required" type="knowledgeSessionTypeEnum"/>
      <xsd:attribute name="kbase" use="required" type="xsd:string"/>
      <xsd:attribute name="id" use="required" type="xsd:ID"/>
      <xsd:attribute name="node" use="optional" type="xsd:string"/>
      <xsd:attribute name="name" use="optional" type="xsd:string"/>

      <xsd:attribute name="listeners" use="optional" type="xsd:string"/-->

    </xsd:complexType>
    </xsd:element>

  <xsd:simpleType name="typeProvider">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="MONGODB" />
      <xsd:enumeration value="CASSANDRA" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== kodoliti/fluid/fluid-core/src/main/resources/fluid.xml
<?xml version="1.0" encoding="UTF-8"?>
<fluid xmlns="http://kodoliti.org/schema/fluid"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:schemaLocation="http://kodoliti.org/schema/fluid http://kodoliti.org/schema/fluid-schema.xsd">
    <system-conf>
        <!--topology-->
        <grid>
        <nodes>
           <node id="1" address="192.168.1.10" />
           <node id="2" address="192.168.1.11" />
        </nodes>
        </grid>
        <!--/topology-->
        <persistence>
            <provider type="MONGODB" />
            <connection-conf driverClass="" 
                             host="127.0.0.1"
                             port="27017"
                             username=""
                             password="" />
        </persistence>
    </system-conf>
    <process-conf>
        <diagram location="" />

        <service-tasks>
            <task class="" ></task>
        </service-tasks>
    </process-conf>
</fluid>
